pipeline {
    agent any

    environment {
        // It's good practice to keep sensitive or specific data like Docker images, remote hosts, and credentials out of the script for security and flexibility.
        DOCKER_IMAGE    = 'noychiffon05/fastapi-webhook:latest' // Ensure this Docker image name is correct and accessible.
        REMOTE_HOST     = 'g64070172@34.142.247.166' // Replace with your actual username and remote IP.
        SSH_CREDENTIALS = 'ssh-prod_instance' // Use the ID of the Jenkins stored SSH credentials.
    }
    
    stages {
        stage('Build Vue.js Application') {
            steps {
                // Change directory to Vue.js project directory and build the application
                dir(VUE_PROJECT_DIR) {
                    sh 'npm install'  // Install dependencies
                    sh 'npm run build'  // Build Vue.js application
                }
            }
        }

        stage('Deploy to Remote Server') {
            steps {
                // Use SSH Agent plugin to setup SSH credentials
                sshagent([SSH_CREDENTIALS]) {
                    // Copy build artifacts to remote server
                    sh "scp -o StrictHostKeyChecking=no -r ${VUE_PROJECT_DIR}/dist/* ${REMOTE_HOST}:~/vue_app/"

                    // You may need to adjust the destination directory path on the remote server
                    // Serve build files using Nginx or any other web server
                    sh "ssh -o StrictHostKeyChecking=no ${REMOTE_HOST} 'sudo cp -r ~/vue_app/* /var/www/html/'"
                }
            }
        }
    }
}
